name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install required packages
        run: sudo apt-get install --yes cmake ninja-build libcurl4-openssl-dev zlib1g-dev libpng-dev libjpeg-dev nettle-dev pkg-config libtinyxml2-dev gettext libseccomp-dev libzstd-dev liblz4-dev liblzo2-dev qtbase5-dev qttools5-dev-tools extra-cmake-modules libkf5kio-dev libkf5widgetsaddons-dev libkf5filemetadata-dev libglib2.0-dev libgtk-3-dev libcairo2-dev libthunarx-3-dev libgsound-dev libnautilus-extension-dev libgtk-4-dev
      - name: Run CMake
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_COVERAGE /gcc -G Ninja
      - name: Run Ninja
        run: cd build && ninja
      - name: Run tests
        run: cd build && LD_LIBRARY_PATH=./lib ctest -V -C Release
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_ignore: extlib/
